### ISSUE TITLE
how to start the game

### ISSUE THREAD

**Issue by xpsycox** [mdodis/OpenSolomonsKey#8]
can you pleas explain easier how to start opensolomonskey? i don't understand quite well

**Comment by mdodis** [comment]
You've compiled it, right? Then run the executable in the build directory from the project's root directory through the command prompt
For Windows that would be: `build\solomons_key.exe`

**Comment by xpsycox** [comment]
Sorry, i don't Know how to code, but i have found your site with the downloadable file. Thancks for the answer. p.s. nice work

**Comment by mdodis** [comment]
Thank you very much! Closing this issue now
